// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlzbOgzaXn4Ewim7OVoo9n-VvBHiZxJcU',
    appId: '1:128267100269:web:73fb406b2b380407f75f64',
    messagingSenderId: '128267100269',
    projectId: 'jtecaa-v2',
    authDomain: 'jtecaa-v2.firebaseapp.com',
    storageBucket: 'jtecaa-v2.firebasestorage.app',
    measurementId: 'G-P1X9KFSTES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1JcyIGWipQMAHD5Z70dyJfY36S3xm5k',
    appId: '1:128267100269:android:f51c334a2cbb6dc8f75f64',
    messagingSenderId: '128267100269',
    projectId: 'jtecaa-v2',
    storageBucket: 'jtecaa-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGZD7E48i3HvGiYJXpoW-amZpqEG47RU',
    appId: '1:128267100269:ios:eab427d3b60bb1d6f75f64',
    messagingSenderId: '128267100269',
    projectId: 'jtecaa-v2',
    storageBucket: 'jtecaa-v2.firebasestorage.app',
    iosBundleId: 'com.jtecaa.jtecaaApp',
  );
}
