// lib/main.dart
//
// Entry point. Architecture §2 philosophy: "Firestore is the last resort" —
// so the very first thing we do after Firebase is spin up Hive (Tier 2 of
// the 4-tier cache pyramid, §6) BEFORE the app widget tree is even built.
//
// ⚠️ CHANGED in Phase 3: `home:` now points to the real `SplashScreen`
// (Phase 3) instead of the temporary Phase 0/2 placeholder widget, which
// has been deleted from this file entirely.
//
// ⚠️ APPENDIX K.6 FIX: `builder:` clamps the system text-scale factor.
// Originally clamped to [0.85, 1.3]; revised to [0.85, 2.0] to respect
// Android/iOS accessibility settings up to 200% (a hard ceiling that
// matches WCAG "AA" recommended max) while still guarding against the
// rare pathological scales some OEMs expose. Every screen/card in this
// app has been made overflow-safe against 200% text scale, so the
// original 1.3 clamp is no longer necessary and was removing the
// accessibility affordance users explicitly requested in system settings.
//
// ⚠️ NEW (Native Splash): `FlutterNativeSplash.preserve()` keeps the
// native launch screen (navy background generated by
// `flutter_native_splash:create`) on screen while Firebase + Hive + FCM
// initialize below — so the user never sees a white flash on cold start.
// It is released from SplashScreen.initState() via
// `FlutterNativeSplash.remove()`.
//
// ⚠️ NEW (Production hardening):
//   - FlutterError.onError routes framework errors to a single handler.
//   - PlatformDispatcher.instance.onError catches async errors that
//     would otherwise silently fail.
//   - Portrait-only orientation lock — this is a phone-first alumni app
//     and landscape layouts weren't designed/verified.
//   - `child!` in the builder now guarded with a null check.

import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/theme/app_theme.dart';
import 'data/datasources/local/hive_service.dart';
import 'data/datasources/remote/fcm_service.dart';
import 'firebase_options.dart';
import 'presentation/providers/settings_provider.dart';
import 'presentation/screens/splash/splash_screen.dart';

void main() async {
  // ── 1. Native splash + binding ────────────────────────────────
  final binding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: binding);

  // ── 2. Orientation lock (portrait-only) ───────────────────────
  // This app has been designed and verified for portrait only. Locking
  // here prevents accidental half-broken landscape on tablets/foldables
  // and matches the paper-profile layout of most alumni apps.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // ── 3. Global error handlers (production safety net) ──────────
  // Catches everything from framework build errors to uncaught async
  // exceptions, so a stray error never leaves the app in a silently
  // broken state during a demo or in the field.
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.presentError(details);
    // TODO(you): swap for a real crash reporter (Crashlytics / Sentry)
    // once analytics is wired. Logging to console for now.
    if (kDebugMode) {
      debugPrint('❌ FlutterError: ${details.exception}');
    }
  };

  PlatformDispatcher.instance.onError = (error, stack) {
    if (kDebugMode) {
      debugPrint('❌ Uncaught async error: $error');
    }
    // Returning true tells the engine the error was handled — prevents
    // the app from hard-crashing on a stray async throw.
    return true;
  };

  // ── 4. Firebase ───────────────────────────────────────────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ── 5. Hive (Tier 2 cache) ────────────────────────────────────
  await HiveService.initBoxes();

  // ── 6. FCM (must register BEFORE runApp so a cold-start tap is
  //         caught by getInitialMessage, see Appendix L.2.2) ──────
  await FCMService.init();

  // ── 7. Launch ─────────────────────────────────────────────────
  runApp(
    const ProviderScope(
      child: JTECAAApp(),
    ),
  );
}

class JTECAAApp extends ConsumerWidget {
  const JTECAAApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);

    return MaterialApp(
      title: 'JTECAA',
      debugShowCheckedModeBanner: false,
      navigatorKey: FCMService.navigatorKey,
      theme: buildJTECAATheme(),
      darkTheme: buildJTECAADarkTheme(),
      themeMode: themeMode,

      // ── Text scale clamp ────────────────────────────────────────
      // Respects system font scaling up to 200% (WCAG AA ceiling) but
      // prevents the rare OEM quirks that go beyond that (some cheap
      // Android skins expose 3x+). The lower bound of 0.85 prevents
      // text from becoming illegibly small on devices set below
      // default for compactness.
      builder: (context, child) {
        final mediaQuery = MediaQuery.of(context);
        final clampedScaler = mediaQuery.textScaler.clamp(
          minScaleFactor: 0.85,
          maxScaleFactor: 2.0,
        );
        return MediaQuery(
          data: mediaQuery.copyWith(textScaler: clampedScaler),
          // ✅ Null-safe: previous `child!` would crash if the framework
          // ever built without a child (rare, but observed in some
          // hot-restart edge cases). Falling back to an empty box means
          // we degrade gracefully instead of dying.
          child: child ?? const SizedBox.shrink(),
        );
      },

      home: const SplashScreen(),
    );
  }
}
