// lib/presentation/screens/splash/splash_screen.dart
//
// Architecture Appendix F.7.1 — 5s forced display, scale+fade animation,
// then navigates based on auth state AND role (§M.5/§M.6): this is where
// the two async streams (authStateProvider, myRoleProvider) converge
// before any navigation decision is made.

import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/constants/app_constants.dart';
import '../../../data/models/user/role_model.dart';
import '../../providers/auth_provider.dart';
import '../../providers/role_provider.dart';
import '../auth/login_screen.dart';
import '../auth/verification_gate_screen.dart';
import '../home/home_screen.dart'; // ⚠️ NEW (Phase 4) — replaces the placeholder
import '../student/student_shell.dart';

class SplashScreen extends ConsumerStatefulWidget {
  const SplashScreen({super.key});

  @override
  ConsumerState<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends ConsumerState<SplashScreen>
    with TickerProviderStateMixin {
  // ── Controllers ───────────────────────────────────────────────────
  late final AnimationController _controller;
  late final AnimationController _bgController;
  late final AnimationController _shineController;
  late final AnimationController _particleController;
  late final AnimationController _progressController;

  late final Animation<double> _scale;
  late final Animation<double> _fade;

  bool _minDurationElapsed = false;
  bool _hasNavigated = false;
  Object? _roleError;

  int _progressPercent = 0;

  final List<_Particle> _particles = [];
  final math.Random _rng = math.Random(42);

  @override
  void initState() {
    super.initState();

    // ⚠️ NEW (Native Splash): the native launch screen (navy background
    // generated by `flutter_native_splash:create`) was held on screen by
    // FlutterNativeSplash.preserve() inside main.dart while Firebase +
    // Hive + FCM initialized. Now that this animated splash is ready to
    // render, release the native one so there is no white flash and no
    // double-splash stack.
    FlutterNativeSplash.remove();

    _controller = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 900));
    _scale = Tween<double>(begin: 0.7, end: 1.0).animate(
        CurvedAnimation(parent: _controller, curve: Curves.easeOutBack));
    _fade = Tween<double>(begin: 0.0, end: 1.0)
        .animate(CurvedAnimation(parent: _controller, curve: Curves.easeOut));

    _bgController =
        AnimationController(vsync: this, duration: const Duration(seconds: 8))
          ..repeat();

    _shineController = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 2600))
      ..repeat();

    _particleController =
        AnimationController(vsync: this, duration: const Duration(seconds: 4))
          ..repeat();

    _progressController = AnimationController(
      vsync: this,
      duration: AppConstants.splashDuration,
    )
      ..addListener(() {
        final pct = (_progressController.value * 100).clamp(0, 100).toInt();
        if (pct != _progressPercent && mounted) {
          setState(() => _progressPercent = pct);
        }
      })
      ..forward();

    _controller.forward();

    for (int i = 0; i < 28; i++) {
      _particles.add(_Particle.random(_rng));
    }

    Timer(AppConstants.splashDuration, () {
      if (mounted) setState(() => _minDurationElapsed = true);
      _maybeNavigate();
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    _bgController.dispose();
    _shineController.dispose();
    _particleController.dispose();
    _progressController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ref.listen(authStateProvider, (_, __) => _maybeNavigate());
    ref.listen(myRoleProvider, (_, __) => _maybeNavigate());

    if (_roleError != null) {
      return _buildErrorScreen(context);
    }

    final theme = Theme.of(context);
    final media = MediaQuery.of(context);
    final size = media.size;

    // ── Responsive scale (small phone → tablet) ──────────────────────
    final shortest = math.min(size.width, size.height);
    final scale = (shortest / 375.0).clamp(0.75, 1.30);

    // ── Text scaler clamp (accessibility-safe) ───────────────────────
    final textScaler = media.textScaler.clamp(
      minScaleFactor: 0.9,
      maxScaleFactor: 1.15,
    );

    // ── Respect user's "reduce motion" preference ────────────────────
    final reduceMotion = media.disableAnimations;

    // Brand palette
    const navy = Color(0xFF1B3A5C);
    const steelBlue = Color(0xFF4A7FA7);
    const lightBlue = Color(0xFF8FB8D1);
    const gold = Color(0xFFE8B84B);

    // Scaled dimensions
    final ringOuter = 220.0 * scale;
    final ringInner = 190.0 * scale;
    final iconCore = 160.0 * scale;
    final iconSize = 88.0 * scale;

    // Reserved bottom panel height (progress + bar + gap + watermark)
    final bottomPanelHeight = 96 * scale;

    // SafeArea insets
    final safeTop = media.padding.top;
    final safeBottom = media.padding.bottom;

    return Scaffold(
      backgroundColor: navy,
      // Force portrait-friendly layout, but landscape will still work
      // since everything is inside SafeArea + scroll-safe zones.
      body: Stack(
        fit: StackFit.expand,
        children: [
          // ── 1. Background ─────────────────────────────────────────
          Positioned.fill(
            child: RepaintBoundary(
              child: AnimatedBuilder(
                animation: Listenable.merge([_bgController, _controller]),
                builder: (context, _) {
                  return CustomPaint(
                    painter: _SplashBackgroundPainter(
                      progress: reduceMotion ? 0.0 : _bgController.value,
                      entrance: _controller.value,
                      navy: navy,
                      steelBlue: steelBlue,
                      lightBlue: lightBlue,
                    ),
                  );
                },
              ),
            ),
          ),

          // ── 2. Curved wave at bottom (fixed) ──────────────────────
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            height: 55 * scale,
            child: IgnorePointer(
              child: ClipPath(
                clipper: _BottomWaveClipper(),
                child: Container(
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                      colors: [
                        lightBlue.withValues(alpha: 0.0),
                        lightBlue.withValues(alpha: 0.10),
                        steelBlue.withValues(alpha: 0.22),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),

          // ── 3. Main content (scroll-safe, leaves bottom space) ────
          Positioned.fill(
            child: SafeArea(
              top: true,
              bottom: false,
              minimum: EdgeInsets.only(top: safeTop > 0 ? 0 : 12),
              child: Padding(
                padding: EdgeInsets.only(bottom: bottomPanelHeight),
                child: Center(
                  child: SingleChildScrollView(
                    physics: const ClampingScrollPhysics(),
                    child: FadeTransition(
                      opacity: _fade,
                      child: ScaleTransition(
                        scale: _scale,
                        child: Padding(
                          padding: EdgeInsets.symmetric(
                            horizontal: 24 * scale,
                            vertical: 12 * scale,
                          ),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              // ── ICON with ring + particles ────
                              SizedBox(
                                width: ringOuter + 40,
                                height: ringOuter + 40,
                                child: Stack(
                                  alignment: Alignment.center,
                                  children: [
                                    if (!reduceMotion)
                                      AnimatedBuilder(
                                        animation: _particleController,
                                        builder: (context, _) {
                                          return CustomPaint(
                                            size: Size(
                                                ringOuter + 40, ringOuter + 40),
                                            painter: _ParticlePainter(
                                              particles: _particles,
                                              progress:
                                                  _particleController.value,
                                              color: gold,
                                              secondaryColor: lightBlue,
                                            ),
                                          );
                                        },
                                      ),
                                    AnimatedBuilder(
                                      animation: Listenable.merge(
                                          [_controller, _shineController]),
                                      builder: (context, _) {
                                        final shineAngle = reduceMotion
                                            ? 0.0
                                            : _shineController.value *
                                                2 *
                                                math.pi;
                                        return Stack(
                                          alignment: Alignment.center,
                                          children: [
                                            Container(
                                              width: ringOuter,
                                              height: ringOuter,
                                              decoration: BoxDecoration(
                                                shape: BoxShape.circle,
                                                gradient: SweepGradient(
                                                  colors: [
                                                    Colors.white
                                                        .withValues(alpha: 0.0),
                                                    lightBlue.withValues(
                                                        alpha: 0.45),
                                                    gold.withValues(
                                                        alpha: 0.35),
                                                    Colors.white
                                                        .withValues(alpha: 0.0),
                                                  ],
                                                  transform: GradientRotation(
                                                      shineAngle),
                                                ),
                                              ),
                                            ),
                                            Container(
                                              width: ringInner,
                                              height: ringInner,
                                              decoration: BoxDecoration(
                                                shape: BoxShape.circle,
                                                color: Colors.white
                                                    .withValues(alpha: 0.06),
                                                boxShadow: [
                                                  BoxShadow(
                                                    color: lightBlue.withValues(
                                                        alpha: 0.45),
                                                    blurRadius: 55 * scale,
                                                    spreadRadius: 8 * scale,
                                                  ),
                                                ],
                                              ),
                                            ),
                                            Container(
                                              width: iconCore,
                                              height: iconCore,
                                              decoration: BoxDecoration(
                                                shape: BoxShape.circle,
                                                gradient: const LinearGradient(
                                                  begin: Alignment.topLeft,
                                                  end: Alignment.bottomRight,
                                                  colors: [
                                                    Color(0xFF4A7FA7),
                                                    Color(0xFF1B3A5C),
                                                  ],
                                                ),
                                                boxShadow: [
                                                  BoxShadow(
                                                    color: Colors.black
                                                        .withValues(
                                                            alpha: 0.35),
                                                    blurRadius: 26 * scale,
                                                    offset:
                                                        Offset(0, 12 * scale),
                                                  ),
                                                ],
                                                border: Border.all(
                                                  color: Colors.white
                                                      .withValues(alpha: 0.25),
                                                  width: 2,
                                                ),
                                              ),
                                              child: Icon(
                                                Icons.school_rounded,
                                                size: iconSize,
                                                color: Colors.white,
                                              ),
                                            ),
                                          ],
                                        );
                                      },
                                    ),
                                  ],
                                ),
                              ),

                              SizedBox(height: 28 * scale),

                              // ── "JTECAA" gradient text ────────
                              FittedBox(
                                fit: BoxFit.scaleDown,
                                child: MediaQuery(
                                  data: media.copyWith(textScaler: textScaler),
                                  child: ShaderMask(
                                    shaderCallback: (bounds) =>
                                        const LinearGradient(
                                      colors: [
                                        Color(0xFFFFFFFF),
                                        Color(0xFF8FB8D1),
                                        Color(0xFFE8B84B),
                                        Color(0xFFFFFFFF),
                                      ],
                                      stops: [0.0, 0.4, 0.7, 1.0],
                                      begin: Alignment.topLeft,
                                      end: Alignment.bottomRight,
                                    ).createShader(bounds),
                                    child: Text(
                                      'JTECAA',
                                      maxLines: 1,
                                      overflow: TextOverflow.ellipsis,
                                      style: theme.textTheme.displayMedium
                                          ?.copyWith(
                                        color: Colors.white,
                                        fontWeight: FontWeight.w900,
                                        fontStyle: FontStyle.italic,
                                        letterSpacing: 7,
                                        height: 1.0,
                                        fontSize: (theme.textTheme.displayMedium
                                                    ?.fontSize ??
                                                45) *
                                            scale,
                                        shadows: [
                                          Shadow(
                                            color: Colors.black
                                                .withValues(alpha: 0.4),
                                            blurRadius: 18 * scale,
                                            offset: Offset(0, 6 * scale),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                              ),

                              SizedBox(height: 12 * scale),

                              FittedBox(
                                fit: BoxFit.scaleDown,
                                child: Row(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    _dot(lightBlue, scale),
                                    _line(lightBlue, scale),
                                    _dot(gold, scale),
                                    _line(gold, scale),
                                    _dot(lightBlue, scale),
                                  ],
                                ),
                              ),

                              SizedBox(height: 14 * scale),

                              FittedBox(
                                fit: BoxFit.scaleDown,
                                child: MediaQuery(
                                  data: media.copyWith(textScaler: textScaler),
                                  child: Text(
                                    'ALUMNI  ASSOCIATION',
                                    maxLines: 1,
                                    overflow: TextOverflow.ellipsis,
                                    style:
                                        theme.textTheme.titleMedium?.copyWith(
                                      color: lightBlue,
                                      fontWeight: FontWeight.w700,
                                      fontStyle: FontStyle.italic,
                                      letterSpacing: 5.0,
                                      fontSize: 14 * scale,
                                    ),
                                  ),
                                ),
                              ),

                              SizedBox(height: 32 * scale),

                              _AnimatedTagline(
                                text: AppConstants.appTagline,
                                controller: _controller,
                                baseDelay: 0.55,
                                stagger: 0.08,
                                color: Colors.white70,
                                fontSize: 13 * scale,
                                textScaler: textScaler,
                                reduceMotion: reduceMotion,
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),

          // ── 4. FIXED bottom panel (progress + bar + watermark) ────
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            child: SafeArea(
              top: false,
              minimum: const EdgeInsets.only(bottom: 8),
              child: Padding(
                padding: EdgeInsets.only(
                  left: 24 * scale,
                  right: 24 * scale,
                  bottom: 8 * scale + (safeBottom > 0 ? 0 : 4),
                ),
                child: FadeTransition(
                  opacity: _fade,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      // ── Progress row (LOADING … %) ──────────
                      ConstrainedBox(
                        constraints: const BoxConstraints(
                          maxWidth: 360,
                          minWidth: 200,
                        ),
                        child: SizedBox(
                          width: size.width * 0.72,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Padding(
                                padding: EdgeInsets.symmetric(
                                  horizontal: 2 * scale,
                                ),
                                child: Row(
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Flexible(
                                      child: Text(
                                        'LOADING....',
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                        style: theme.textTheme.labelSmall
                                            ?.copyWith(
                                          color: Colors.white70,
                                          letterSpacing: 3,
                                          fontWeight: FontWeight.w600,
                                          fontSize: 10 * scale,
                                        ),
                                      ),
                                    ),
                                    SizedBox(width: 12 * scale),
                                    SizedBox(
                                      width: 44 * scale,
                                      child: Text(
                                        '$_progressPercent%',
                                        textAlign: TextAlign.right,
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                        style: theme.textTheme.labelSmall
                                            ?.copyWith(
                                          color: gold,
                                          letterSpacing: 1.2,
                                          fontWeight: FontWeight.w800,
                                          fontSize: 11 * scale,
                                          fontFeatures: const [
                                            FontFeature.tabularFigures(),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              SizedBox(height: 8 * scale),
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: LinearProgressIndicator(
                                  minHeight: 3,
                                  value: _progressController.value,
                                  backgroundColor:
                                      Colors.white.withValues(alpha: 0.12),
                                  valueColor:
                                      const AlwaysStoppedAnimation<Color>(gold),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),

                      SizedBox(height: 14 * scale),

                      // ── Watermark ──────────────────────────
                      MediaQuery(
                        data: media.copyWith(textScaler: textScaler),
                        child: Text(
                          'Powered by  JTECAA.',
                          textAlign: TextAlign.center,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: theme.textTheme.labelSmall?.copyWith(
                            color: Colors.white70,
                            letterSpacing: 1.6,
                            fontWeight: FontWeight.w600,
                            fontSize: 10 * scale,
                            fontStyle: FontStyle.italic,
                            shadows: [
                              Shadow(
                                color: Colors.black.withValues(alpha: 0.6),
                                blurRadius: 6,
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _dot(Color color, double scale) => Container(
        width: 6 * scale,
        height: 6 * scale,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          color: color,
          boxShadow: [
            BoxShadow(
              color: color.withValues(alpha: 0.7),
              blurRadius: 8 * scale,
              spreadRadius: 1,
            ),
          ],
        ),
      );

  Widget _line(Color color, double scale) => Container(
        width: 55 * scale,
        height: 1.5,
        margin: EdgeInsets.symmetric(horizontal: 8 * scale),
        decoration: BoxDecoration(
          gradient: LinearGradient(colors: [
            color.withValues(alpha: 0.0),
            color,
            color.withValues(alpha: 0.0),
          ]),
        ),
      );

  // ─────────────────────────────────────────────────────────────────
  // ⚠️ ALL LOGIC BELOW IS UNTOUCHED — only visuals above were upgraded.
  // ─────────────────────────────────────────────────────────────────

  Widget _buildErrorScreen(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      backgroundColor: theme.colorScheme.surface,
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.cloud_off_outlined,
                    size: 56, color: theme.colorScheme.error),
                const SizedBox(height: 16),
                Text('Could not connect',
                    style: theme.textTheme.titleLarge,
                    textAlign: TextAlign.center),
                const SizedBox(height: 8),
                Text(
                  '$_roleError',
                  textAlign: TextAlign.center,
                  style: theme.textTheme.bodySmall
                      ?.copyWith(color: theme.colorScheme.onSurfaceVariant),
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: () {
                    final uid = ref.read(authStateProvider).valueOrNull?.uid;
                    setState(() => _roleError = null);
                    if (uid != null) {
                      ref.invalidate(roleProvider(uid));
                    }
                    _maybeNavigate();
                  },
                  child: const Text('Retry'),
                ),
                const SizedBox(height: 12),
                TextButton(
                  onPressed: () async {
                    await ref.read(authControllerProvider.notifier).signOut();
                    if (!mounted) {
                      return;
                    }
                    setState(() => _roleError = null);
                  },
                  child: const Text('Sign out'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  void _maybeNavigate() {
    if (!_minDurationElapsed || _hasNavigated || !mounted) {
      return;
    }

    final authAsync = ref.read(authStateProvider);
    if (authAsync.isLoading) {
      return;
    }

    final user = authAsync.valueOrNull;
    if (user == null) {
      _navigateOnce(const LoginScreen());
      return;
    }
    if (!user.emailVerified) {
      _navigateOnce(const VerificationGateScreen());
      return;
    }

    final roleAsync = ref.read(myRoleProvider);
    if (roleAsync.isLoading) {
      return;
    }
    if (roleAsync.hasError) {
      setState(() => _roleError = roleAsync.error);
      return;
    }
    final role = roleAsync.valueOrNull;
    if (role == null) {
      return;
    }

    if (role == SignupRole.student) {
      _navigateOnce(const StudentShell());
    } else {
      _navigateOnce(const HomeScreen());
    }
  }

  void _navigateOnce(Widget screen) {
    if (_hasNavigated || !mounted) {
      return;
    }
    _hasNavigated = true;
    Navigator.of(context).pushAndRemoveUntil(
      MaterialPageRoute(builder: (_) => screen),
      (route) => false,
    );
  }
}

// ─────────────────────────────────────────────────────────────────────
// Word-by-word animated tagline
// ─────────────────────────────────────────────────────────────────────
class _AnimatedTagline extends StatelessWidget {
  const _AnimatedTagline({
    required this.text,
    required this.controller,
    required this.baseDelay,
    required this.stagger,
    required this.color,
    required this.fontSize,
    required this.textScaler,
    required this.reduceMotion,
  });

  final String text;
  final AnimationController controller;
  final double baseDelay;
  final double stagger;
  final Color color;
  final double fontSize;
  final TextScaler textScaler;
  final bool reduceMotion;

  @override
  Widget build(BuildContext context) {
    final words = text.split(' ');

    // If reduceMotion is on, show the tagline as a plain text — no stagger.
    if (reduceMotion) {
      return MediaQuery(
        data: MediaQuery.of(context).copyWith(textScaler: textScaler),
        child: Text(
          text,
          textAlign: TextAlign.center,
          style: TextStyle(
            color: color,
            fontSize: fontSize,
            letterSpacing: 0.8,
            fontStyle: FontStyle.italic,
            fontWeight: FontWeight.w500,
          ),
        ),
      );
    }

    return MediaQuery(
      data: MediaQuery.of(context).copyWith(textScaler: textScaler),
      child: Wrap(
        alignment: WrapAlignment.center,
        spacing: 8,
        runSpacing: 4,
        children: List.generate(words.length, (i) {
          final start = baseDelay + (i * stagger);
          final end = (start + 0.25).clamp(0.0, 1.0);
          return AnimatedBuilder(
            animation: controller,
            builder: (context, child) {
              final t =
                  ((controller.value - start) / (end - start)).clamp(0.0, 1.0);
              final curved = Curves.easeOutCubic.transform(t);
              return Opacity(
                opacity: curved,
                child: Transform.translate(
                  offset: Offset(0, 10 * (1 - curved)),
                  child: child,
                ),
              );
            },
            child: Text(
              words[i],
              style: TextStyle(
                color: color,
                fontSize: fontSize,
                letterSpacing: 0.8,
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.w500,
              ),
            ),
          );
        }),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────
// Bottom curved wave clipper
// ─────────────────────────────────────────────────────────────────────
class _BottomWaveClipper extends CustomClipper<Path> {
  @override
  Path getClip(Size size) {
    final path = Path();
    path.moveTo(0, size.height * 0.55);
    path.quadraticBezierTo(
      size.width * 0.25,
      size.height * 0.15,
      size.width * 0.5,
      size.height * 0.45,
    );
    path.quadraticBezierTo(
      size.width * 0.75,
      size.height * 0.75,
      size.width,
      size.height * 0.35,
    );
    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);
    path.close();
    return path;
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
}

// ─────────────────────────────────────────────────────────────────────
// Sparkle particle system
// ─────────────────────────────────────────────────────────────────────
class _Particle {
  _Particle({
    required this.baseAngle,
    required this.radiusFactor,
    required this.size,
    required this.speed,
    required this.phase,
    required this.colorMix,
  });

  final double baseAngle;
  final double radiusFactor;
  final double size;
  final double speed;
  final double phase;
  final double colorMix;

  factory _Particle.random(math.Random rng) {
    return _Particle(
      baseAngle: rng.nextDouble() * 2 * math.pi,
      radiusFactor: 0.70 + rng.nextDouble() * 0.55,
      size: 1.5 + rng.nextDouble() * 2.0,
      speed: 0.3 + rng.nextDouble() * 0.9,
      phase: rng.nextDouble(),
      colorMix: rng.nextDouble(),
    );
  }
}

class _ParticlePainter extends CustomPainter {
  _ParticlePainter({
    required this.particles,
    required this.progress,
    required this.color,
    required this.secondaryColor,
  });

  final List<_Particle> particles;
  final double progress;
  final Color color;
  final Color secondaryColor;

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(size.width / 2, size.height / 2);
    final baseRadius = size.shortestSide * 0.32;

    for (final p in particles) {
      final t = (progress * p.speed + p.phase) % 1.0;

      final angle = p.baseAngle + t * 0.6;
      final radius = baseRadius * p.radiusFactor * (0.9 + t * 0.15);

      final dx = center.dx + math.cos(angle) * radius;
      final dy = center.dy + math.sin(angle) * radius;

      final fade = math.sin(t * math.pi).clamp(0.0, 1.0);
      if (fade <= 0.02) continue;

      final mixed = Color.lerp(color, secondaryColor, p.colorMix)!;
      final paint = Paint()
        ..color = mixed.withValues(alpha: 0.85 * fade)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 1.2);

      canvas.drawCircle(Offset(dx, dy), p.size, paint);

      final haloPaint = Paint()
        ..color = mixed.withValues(alpha: 0.18 * fade)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 6);
      canvas.drawCircle(Offset(dx, dy), p.size * 2.4, haloPaint);
    }
  }

  @override
  bool shouldRepaint(covariant _ParticlePainter old) =>
      old.progress != progress;
}

// ─────────────────────────────────────────────────────────────────────
// Background painter (gradient + grid + orbs + diagonal)
// ─────────────────────────────────────────────────────────────────────
class _SplashBackgroundPainter extends CustomPainter {
  _SplashBackgroundPainter({
    required this.progress,
    required this.entrance,
    required this.navy,
    required this.steelBlue,
    required this.lightBlue,
  });

  final double progress;
  final double entrance;
  final Color navy;
  final Color steelBlue;
  final Color lightBlue;

  @override
  void paint(Canvas canvas, Size size) {
    final bgRect = Offset.zero & size;
    final bgPaint = Paint()
      ..shader = LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [
          navy,
          Color.lerp(navy, steelBlue, 0.45)!,
          navy,
        ],
        stops: const [0.0, 0.5, 1.0],
      ).createShader(bgRect);
    canvas.drawRect(bgRect, bgPaint);

    final center = Offset(size.width / 2, size.height * 0.40);
    final radius = size.longestSide * 0.75;
    final glowPaint = Paint()
      ..shader = RadialGradient(
        colors: [
          lightBlue.withValues(alpha: 0.18),
          navy.withValues(alpha: 0.0),
        ],
      ).createShader(Rect.fromCircle(center: center, radius: radius));
    canvas.drawCircle(center, radius, glowPaint);

    final gridPaint = Paint()
      ..color = Colors.white.withValues(alpha: 0.03)
      ..strokeWidth = 1;
    const gap = 48.0;
    for (double x = 0; x < size.width; x += gap) {
      canvas.drawLine(Offset(x, 0), Offset(x, size.height), gridPaint);
    }
    for (double y = 0; y < size.height; y += gap) {
      canvas.drawLine(Offset(0, y), Offset(size.width, y), gridPaint);
    }

    final orbs = [
      _Orb(Offset(size.width * 0.12, size.height * 0.18), 100, 0.0, lightBlue),
      _Orb(Offset(size.width * 0.88, size.height * 0.28), 70, 0.35, steelBlue),
      _Orb(Offset(size.width * 0.18, size.height * 0.85), 130, 0.65, steelBlue),
      _Orb(Offset(size.width * 0.92, size.height * 0.82), 80, 0.9, lightBlue),
    ];
    for (final orb in orbs) {
      final t = (progress + orb.phase) % 1.0;
      final dy = (t - 0.5) * 30;
      final paint = Paint()
        ..color = orb.color.withValues(alpha: 0.10)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 40);
      canvas.drawCircle(orb.center.translate(0, dy), orb.radius, paint);
    }

    final linePaint = Paint()
      ..color = lightBlue.withValues(alpha: 0.07)
      ..strokeWidth = 1.2;
    canvas.drawLine(
      Offset(0, size.height * 0.78),
      Offset(size.width, size.height * 0.32),
      linePaint,
    );
  }

  @override
  bool shouldRepaint(covariant _SplashBackgroundPainter old) =>
      old.progress != progress || old.entrance != entrance;
}

class _Orb {
  const _Orb(this.center, this.radius, this.phase, this.color);
  final Offset center;
  final double radius;
  final double phase;
  final Color color;
}
